ALTER SESSION SET CONTAINER = XEPDB1;

-- Tables imported from legacy Program_*.xls files (via oracle_import_xepdb1.sql):
-- PLU, CASHIER, CLERK, CONDIMENT, CUSTOMKEYBOARD, DEPARTMENT, DEPARTMENTGROUP,
-- DISCOUNT, FOODPACKAGE, FOREIGNCURRENCY, I18NPARAMETER, PAYMENTTYPE, PLUSTOCKIN,
-- RECEIPTHEADERFOOTER, SERVICEFEE, SYSTEMPASSWORD, SYTEMPARAMETER, "TABLE", TAX, VIP

-- Sales (operational data generated by the POS)
CREATE TABLE sales (
  id VARCHAR2(64) PRIMARY KEY,
  receipt_number VARCHAR2(100),
  items_json CLOB,
  subtotal NUMBER(10,2),
  tax NUMBER(10,2),
  discount NUMBER(10,2),
  total NUMBER(10,2),
  payment_method VARCHAR2(20),
  customer_id VARCHAR2(255),
  customer_name VARCHAR2(255),
  cashier_id VARCHAR2(255),
  cashier_name VARCHAR2(255),
  created_at VARCHAR2(30)
);

-- Sequences for ID generation (used by legacy app, kept for reference)
-- CREATE SEQUENCE seq_product_id START WITH 1 INCREMENT BY 1;
-- CREATE SEQUENCE seq_category_id START WITH 1 INCREMENT BY 1;
-- CREATE SEQUENCE seq_customer_id START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_sale_id START WITH 1 INCREMENT BY 1;
